# This is a basic workflow to help you get started with Actions

name: Hello secrets and vars

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set global environment variable
env:
  ENVIRONMENT: acc

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runner's shell
      - name: check environment
        run: |
          if [ "$SECRET" = "${{ secrets.IS_THIS_REALLY_SECURE }}" ]; then
            echo "Pass!"
          else
            exit 1
          fi
        env:
          SECRET: I Dunno #FIXME reference a secret here to set this env variable you may only edit this line

      # Runs a set of commands using the runner's shell
      - name: check environment
        run: |
          if [ "$VAR" = "${{ vars.NOT_A_SECRET }}" ]; then
            echo "Pass!"
          else
            exit 1
          fi
        env:
          VAR: I Dunno #FIXME reference a var here to set this env variable you may only edit this line